USE Ashu
EXEC sp_configure 'show advanced options', '1' ;
go
RECONFIGURE ;
go
EXEC sp_configure 'clr enabled', '1'
go
RECONFIGURE ;
go


ALTER DATABASE Ashu SET ENABLE_BROKER WITH ROLLBACK IMMEDIATE
ALTER DATABASE Ashu SET NEW_BROKER 
ALTER DATABASE Ashu SET ENABLE_BROKER
GRANT SUBSCRIBE QUERY NOTIFICATIONS TO ashu

